name: ci
on:
  push:

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        platform:
          - name: windows
            runner: windows-latest

          - name: mac
            runner: macos-latest

          - name: linux
            runner: ubuntu-latest

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v3

      - run: RUSTFLAGS="-C strip=symbols" cargo build --release

      - run: echo "ARTIFACT=$(find target/release/ -maxdepth 1 -type f -perm -u+x)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ env.ARTIFACT }}

  create_release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Variables
        id: vars
        run: echo "::set-output name=version::${GITHUB_REF_NAME#v}"

      - shell: pwsh
        run: |
          Get-ChildItem -Path "artifacts" -Recurse -Filter "lunar_launcher_inject*" |
            Move-Item  -Destination { "artifacts/$($_.BaseName)-$($_.Directory.Name)-x64$($_.Extension)" }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.version }}
          draft: true
          files: |
            ./artifacts/*