name: ci
on:
  release:
    types: [created]

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        platform:
          - { runner: windows-latest, name: windows }
          - { runner: macos-latest, name: mac }
          - { runner: ubuntu-20.04, name: linux }

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@nightly

      - name: Build
        run: |
          artifact=lunar-launcher-inject-${{ matrix.platform.name }}-${{ github.event.release.name }}${{ matrix.platform.name == 'windows' && '.exe' || '' }}
          echo "ARTIFACT=$artifact" >> $GITHUB_OUTPUT
          cargo rustc --release -- -o $artifact

      - name: Upload Executable
        run: gh release upload $GITHUB_REF_NAME ${{ steps.build.outputs.ARTIFACT }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}