name: Upload Release Artifacts

on:
  release:
    types: [created]

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        platform:
          - { runner: windows-latest, name: windows }
          - { runner: macos-latest, name: mac }
          - { runner: ubuntu-latest, name: linux }
        include:
          - exe: lunar-launcher-inject-${{ matrix.platform.name }}-${{ github.event.release.name }}${{ matrix.platform.name == 'windows' && '.exe' || '' }}

    runs-on: ${{ matrix.platform.runner }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      run: GOARCH=amd64 go build -v -ldflags '-s -w' -o ${{ matrix.exe }}

    - name: Upload Executable
      run: gh release upload ${GITHUB_REF_NAME} ${{ matrix.exe }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}