name: Upload Release Artifacts

on:
  release:
    types: [created]

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        platform: [
          { runner: windows-latest, exe: lunar-launcher-inject-windows.exe },
          { runner: macos-latest, exe: lunar-launcher-inject-mac },
          { runner: ubuntu-latest, exe: lunar-launcher-inject-linux }
        ]
    runs-on: ${{ matrix.platform.runner }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      run: GOARCH=amd64 go build -v -o ${{ matrix.platform.exe }} -ldflags "-s -w"

    - name: Upload Executable
      run: gh release upload ${GITHUB_REF_NAME} ${{ matrix.platform.exe }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}